### PR TITLE
Make missing atlas image an error in the editor too

### LINKED ISSUE #188: Show build error if spine scene can't be loaded
If there is no image in atlas which needed for spine scene it shows an error only in scene:
CleanShot 2024-10-22 at 10 06 32@2x

But the game builds and exits when it's trying to load such a scene :
```
INFO:ENGINE: Initialised sound device 'default'
ERROR:SPINEC: Failed to read spine skeleton for /assets/coins/coin.spinescenec: (null)
WARNING:RESOURCE: Unable to create resource: /assets/coins/coin.spinescenec: INVALID_DATA
WARNING:RESOURCE: Unable to create resource: /_generated_3b7dfa95.spinemodelc: INVALID_DATA
WARNING:RESOURCE: Unable to create resource: /_generated_e2b44320.goc: INVALID_DATA
ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_e2b44320.goc.
WARNING:RESOURCE: Unable to create resource: /main/main.collectionc: FORMAT_ERROR
INFO:DEFOLDIMGUI: FinalizeDefoldImGui
INFO:DEFOLDIMGUI: imgui_Shutdown
ERROR:RESOURCE: Leaked resources:
ERROR:RESOURCE: Resource: /assets/coins/coin-pro.spinejsonc  ref count: 1
```

The extension should show a build error in such cases (bundle error in bob as well)

### PR DESCRIPTION
**Pull request by vlaaad**
Fixes #188

### CODE REVIEW

File: defold-spine/editor/src/spineext.clj [hunk 1]
```diff
@@ -552,10 +552,10 @@
   (let [^Throwable error (if (instance? java.lang.reflect.InvocationTargetException error) (.getCause error) error)
         msg (.getMessage error)
         path (resource/resource->proj-path resource)
-        msg-missing-image "Region not found"]
+        msg-missing-image "Region not found: "]
```
Comment (vlaaad) [inline defold-spine/editor/src/spineext.clj:555]: Previously, the shown error looked like this: `Atlas is missing image: : image-name`. Now we strip the duplicated `: `

File: defold-spine/editor/src/spineext.clj [hunk 2]
```diff
@@ -668,10 +668,18 @@
...
 
-(g/defnk produce-spine-scene-own-build-errors [_node-id atlas spine-json]
+(g/defnk produce-spine-scene-own-build-errors [_node-id atlas spine-json texture-set-pb spine-json-content]
   (g/package-errors _node-id
                     (validate-scene-atlas _node-id atlas)
-                    (validate-scene-spine-json _node-id spine-json)))
+                    (validate-scene-spine-json _node-id spine-json)
+                    (when (and texture-set-pb spine-json-content)
+                      (try
+                        (plugin-load-file-from-buffer
```
Comment (vlaaad) [inline defold-spine/editor/src/spineext.clj:677]: The pointer calls `SPINE_Destroy` in its `finalize` method, so we can rely on GC here.

**Review by matgis — APPROVED** [review]
LGTM!
