### PR TITLE
Don't send messages from previous mixing animation

### LINKED ISSUE #72: Wrong animation_id in callback during blend, later callback not sent
If a one-shot animation (PLAYBACK_ONCE_FORWARD) is played towards the end of a looping animation, with a blend such that a loop of the first animation occurs during the blend, the wrong animation_id is passed in the callback and subsequent play_anim calls behave unexpectedly.

I've reproduced this in the example (see below for attachment) with the following changes:
1. The idle animation is played by itself with no aiming/IK :
`spine.play_anim(self.url, "idle", go.PLAYBACK_LOOP_FORWARD)`
2. The death animation is played with a blend when clicking the mouse
`spine.play_anim(self.url, "death", go.PLAYBACK_ONCE_FORWARD, { blend_duration = 0.5  }, callback)`
3. The callback plays the idle animation again when the death animation completes - this is similar to the behaviour in our game which worked with the old runtime, but not now
```
if message_id == hash("spine_animation_done") and message.animation_id == hash("death") then
	spine.play_anim(self.url, "idle", go.PLAYBACK_LOOP_FORWARD, { })
end
```
To reproduce:
1. Replace main.script in the example with the attached version.
2. When the character is raising the gun, at about the midway point, click the mouse. The current cursor value is printed - the bug occurs when the cursor is a high value / towards the end of the idle animation.
3. Wait for the end of the death animation
4. If the animation_id printed to the console by the callback is hash: [death], then the idle anim will correctly start.
5. If the animation id is hash: [idle], then the bug has been reproduced. The callback was incorrectly called for the idle animation, and then you will also see that the spine_animation_done message was wrongly sent for the death animation, and handled by on_message .
[main.zip](https://github.com/defold/extension-spine/files/8411914/main.zip)

### PR DESCRIPTION
**Pull request by JCash**
FIxes #72

### CODE REVIEW

File: defold-spine/src/comp_spine_model.cpp [hunk 1]
```diff
@@ -467,19 +467,34 @@ namespace dmSpine
...
+            // }
             case SP_ANIMATION_COMPLETE:
             {
+                if (entry->mixingTo != 0)
+                {
+                    // While mixing, the previous animation completed.
+                    // The problem is that the track is already owned by the new animation, and we
+                    // cannot call the previous callback (as we haven't stored it)
+                    return;
+                }
```
Comment (JCash) [inline defold-spine/src/comp_spine_model.cpp:496]: The issue was that the message (SP_ANIMATION_COMPLETE) comes _after_ we've already stored the information for the target animation.
Assuming we don't want to send an event from the previous animation (we have a new target animation, with a new callback), we can simply skip this event.

Comment (AGulev) [reply defold-spine/src/comp_spine_model.cpp:496]: It looks logical. It's more like a bugfix and I hope it will not be a breaking change for somebody

**Review by AGulev — APPROVED** [review]
